/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import clases.metodos;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.net.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author omar_
 */
public class Jugador extends javax.swing.JFrame {
   String tiempo;
   Thread hilo;
   boolean r=true;
    public static int segundero = 1000;
    /**
     * Creates new form Jugador
     */
    public Jugador() {
        initComponents();
        int hora,minutos,segundos; 
        jtext.setEditable(false);
        jtext1.setEditable(false);
        jhora.setEditable(false);
        Calendar calendario = Calendar.getInstance();
        hora =calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);
        
        metodos met = new metodos();
        jhora.setText(met.mostrar(hora)+":"+met.mostrar(minutos)+":"+met.mostrar(segundos));
        //hilo
        int seg,min,hor;
        
        hilo = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        int segaux, minaux, horaux;
                        while(r){
                                tiempo = jhora.getText();

                                segaux = Integer.parseInt(tiempo.substring(tiempo.lastIndexOf(":")+1));
                                minaux = Integer.parseInt(tiempo.substring(tiempo.indexOf(":")+1,tiempo.lastIndexOf(":")));
                                horaux = Integer.parseInt(tiempo.substring(0,2));
                                if(segaux <59){ 
                                    segaux++;
                                    }
                                else{
                                    segaux=0;
                                    if(minaux<59) 
                                       {
                                        minaux++;
                                       }
                                    else{
                                        minaux=0;
                                        if(horaux<23) {
                                            horaux++;
                                        }
                                        else {
                                            horaux=0;
                                        }
                                    }
                                }

                                jhora.setText(met.mostrar(horaux)+":"+met.mostrar(minaux)+":"+met.mostrar(segaux));
                                Thread.sleep(segundero);
                        }
                        } catch (Exception ex) {
                            System.out.println("Error en hilo: "+ex);
                        }
                }
            });
        hilo.start();//corremos el hilo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmodificar = new javax.swing.JButton();
        jmensaje = new javax.swing.JTextField();
        jtext = new javax.swing.JTextField();
        jhora = new javax.swing.JTextField();
        jenviar = new javax.swing.JButton();
        jtext1 = new javax.swing.JTextField();
        jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jmodificar.setBackground(new java.awt.Color(0, 0, 102));
        jmodificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jmodificar.setForeground(new java.awt.Color(255, 255, 255));
        jmodificar.setText("Modificar");
        jmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 120, 30));
        getContentPane().add(jmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 490, 30));

        jtext.setBackground(new java.awt.Color(0, 0, 51));
        jtext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtext.setForeground(new java.awt.Color(255, 255, 255));
        jtext.setText("Escribe el mensaje:");
        jtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextActionPerformed(evt);
            }
        });
        getContentPane().add(jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, 30));

        jhora.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jhora.setText("12:00:00");
        jhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhoraActionPerformed(evt);
            }
        });
        getContentPane().add(jhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 110, 40));

        jenviar.setBackground(new java.awt.Color(0, 0, 102));
        jenviar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jenviar.setForeground(new java.awt.Color(255, 255, 255));
        jenviar.setText("Enviar");
        jenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenviarActionPerformed(evt);
            }
        });
        getContentPane().add(jenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 120, 30));

        jtext1.setBackground(new java.awt.Color(38, 6, 56));
        jtext1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtext1.setForeground(new java.awt.Color(255, 255, 255));
        jtext1.setText("     Team:   The Avengers");
        jtext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 280, 30));

        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodificarActionPerformed
       
        modhora md=new modhora();
        md.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jmodificarActionPerformed

    private void jtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextActionPerformed

    private void jhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhoraActionPerformed

    private void jenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenviarActionPerformed
        try{
            //System.out.println("Cliente iniciado...");
            String host = JOptionPane.showInputDialog("Escriba la direccion del servidor:");
            int pto = Integer.parseInt(JOptionPane.showInputDialog("Escriba el puerto:"));
            /**
            System.out.println("Escriba la direccion del servidor:");
            String host = br1.readLine();
            System.out.println("\nEscriba el puerto:");
            int pto=Integer.parseInt(br1.readLine());
            */
            Socket cl = new Socket(host, pto);//creamos socket
            String mensaje = jmensaje.getText();
            PrintWriter pw=new PrintWriter(new OutputStreamWriter(cl.getOutputStream()));
            pw.println(mensaje);
            pw.flush();
            pw.close();            
            cl.close();//matamos socket
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jenviarActionPerformed

    private void jtext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jenviar;
    private javax.swing.JLabel jfondo;
    private javax.swing.JTextField jhora;
    private javax.swing.JTextField jmensaje;
    private javax.swing.JButton jmodificar;
    private javax.swing.JTextField jtext;
    private javax.swing.JTextField jtext1;
    // End of variables declaration//GEN-END:variables
}
