/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.metodos;

/**
 *
 * @author omar_
 */
public class modhora extends javax.swing.JFrame {
    Thread hilo;
    int aux1=0,aux2=0,aux3=0;
    public static int segundero = 1000;
    boolean r=true;
    /**
     * Creates new form modhora
     */
    public modhora() {
        initComponents();
        int seg,min,hor;
        jtiempo.setEditable(false);
        metodos met = new metodos();
        Jugador jug=new Jugador();
        hilo = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        int segaux, minaux, horaux;
                        String t;
                        
                        while(r){
                                t = jug.tiempo;

                                segaux = Integer.parseInt(t.substring(t.lastIndexOf(":")+1));
                                minaux = Integer.parseInt(t.substring(t.indexOf(":")+1,t.lastIndexOf(":")));
                                horaux = Integer.parseInt(t.substring(0,2));
                                if(segaux <59){ 
                                    segaux++;
                                    }
                                else{
                                    segaux=0;
                                    if(minaux<59) 
                                       {
                                        minaux++;
                                       }
                                    else{
                                        minaux=0;
                                        if(horaux<23) {
                                            horaux++;
                                        }
                                        else {
                                            horaux=0;
                                        }
                                    }
                                }

                                jtiempo.setText(met.mostrar(horaux)+":"+met.mostrar(minaux)+":"+met.mostrar(segaux));
                                Thread.sleep(segundero);
                                
                        }
                        } catch (Exception ex) {
                            System.out.println("Error en hilo: "+ex);
                        }
                }
            });
        hilo.start();//corremos el hilo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtiempo = new javax.swing.JTextField();
        jseg = new javax.swing.JButton();
        jmin = new javax.swing.JButton();
        jhora = new javax.swing.JButton();
        jtext1 = new javax.swing.JLabel();
        jregresar = new javax.swing.JButton();
        jtext2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mhora = new javax.swing.JTextField();
        mmin = new javax.swing.JTextField();
        mseg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtiempo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jtiempo.setForeground(new java.awt.Color(0, 0, 51));
        jtiempo.setText("00:00:00");
        getContentPane().add(jtiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 40));

        jseg.setBackground(new java.awt.Color(0, 0, 51));
        jseg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jseg.setForeground(new java.awt.Color(255, 255, 255));
        jseg.setText("+");
        jseg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsegActionPerformed(evt);
            }
        });
        getContentPane().add(jseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jmin.setBackground(new java.awt.Color(0, 0, 51));
        jmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jmin.setForeground(new java.awt.Color(255, 255, 255));
        jmin.setText("+");
        jmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jminActionPerformed(evt);
            }
        });
        getContentPane().add(jmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jhora.setBackground(new java.awt.Color(0, 0, 51));
        jhora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jhora.setForeground(new java.awt.Color(255, 255, 255));
        jhora.setText("+");
        jhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhoraActionPerformed(evt);
            }
        });
        getContentPane().add(jhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jtext1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtext1.setText("Modificar Reloj");
        getContentPane().add(jtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fle1.jpg"))); // NOI18N
        jregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregresarActionPerformed(evt);
            }
        });
        getContentPane().add(jregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 50, 40));

        jtext2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtext2.setText("Hora actual:");
        getContentPane().add(jtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText(":");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 10, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText(":");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 10, 30));

        mhora.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mhora.setText("00");
        getContentPane().add(mhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        mmin.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mmin.setText("00");
        getContentPane().add(mmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        mseg.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mseg.setText("00");
        getContentPane().add(mseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jfondo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoazul.jpg"))); // NOI18N
        getContentPane().add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhoraActionPerformed
        metodos met= new metodos();
        if(aux1<23){
        aux1=aux1+1;
        }
        else{
        aux1=0;
        }
        mhora.setText(met.mostrar(aux1));
        
    }//GEN-LAST:event_jhoraActionPerformed

    private void jminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jminActionPerformed
        metodos met= new metodos();
        if(aux2<59){
        aux2=aux2+1;
        }
        else{
        aux2=0;
        aux1=aux1+1;
        mhora.setText(met.mostrar(aux1));
        }
        mmin.setText(met.mostrar(aux2));
    }//GEN-LAST:event_jminActionPerformed

    private void jsegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsegActionPerformed
        metodos met= new metodos();
        if(aux3<59){
        aux3=aux3+1;
        }
        else{
        aux3=0;
        aux2=aux2+1;
        mmin.setText(met.mostrar(aux2));
        }
        mseg.setText(met.mostrar(aux3));
    }//GEN-LAST:event_jsegActionPerformed

    private void jregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregresarActionPerformed
        Jugador jug=new Jugador();
        jug.setVisible(true);
        this.setVisible(false);      
        
    }//GEN-LAST:event_jregresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jugador jug=new Jugador();
        metodos met =new metodos();
        jug.tiempo=met.mostrar(aux1)+":"+met.mostrar(aux2)+":"+met.mostrar(aux3);
        r=false;
        jug.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modhora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modhora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modhora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modhora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modhora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jfondo;
    private javax.swing.JButton jhora;
    private javax.swing.JButton jmin;
    private javax.swing.JButton jregresar;
    private javax.swing.JButton jseg;
    private javax.swing.JLabel jtext1;
    private javax.swing.JLabel jtext2;
    private javax.swing.JTextField jtiempo;
    private javax.swing.JTextField mhora;
    private javax.swing.JTextField mmin;
    private javax.swing.JTextField mseg;
    // End of variables declaration//GEN-END:variables
}
