/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socketnicolai;
import clases.metodos;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.net.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Nicolai
 */
public class server_frame extends javax.swing.JFrame {
    String tiempo;
    Thread hilo;
    boolean r=true;
    public static int segundero = 1000;
    /**
     * Creates new form server_frame
     */
    
    public String clase(){
        tiempo = jhora.getText();
        return tiempo;
    }
    
    
    public server_frame() {
        initComponents();
        jtext1.setEditable(false);jhora.setEditable(false);
        int hora = (int) (Math.random()*24+0);
        int minutos = (int) (Math.random()*60+0);
        int segundos = (int) (Math.random()*60+0);
        metodos met = new metodos();
        jhora.setText(met.mostrar(hora)+":"+met.mostrar(minutos)+":"+met.mostrar(segundos));
        //hilo
        int seg,min,hor;
        
        hilo = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        int segaux, minaux, horaux;
                        while(r){
                                tiempo = jhora.getText();

                                segaux = Integer.parseInt(tiempo.substring(tiempo.lastIndexOf(":")+1));
                                minaux = Integer.parseInt(tiempo.substring(tiempo.indexOf(":")+1,tiempo.lastIndexOf(":")));
                                horaux = Integer.parseInt(tiempo.substring(0,2));
                                if(segaux <59){ 
                                    segaux++;
                                    }
                                else{
                                    segaux=0;
                                    if(minaux<59) 
                                       {
                                        minaux++;
                                       }
                                    else{
                                        minaux=0;
                                        if(horaux<23) {
                                            horaux++;
                                        }
                                        else {
                                            horaux=0;
                                        }
                                    }
                                }

                                jhora.setText(met.mostrar(horaux)+":"+met.mostrar(minaux)+":"+met.mostrar(segaux));
                                Thread.sleep(segundero);
                        }
                        } catch (Exception ex) {
                            System.out.println("Error en hilo: "+ex);
                        }
                }
            });
        hilo.start();//corremos el hilo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfondo = new javax.swing.JLabel();
        jhora = new javax.swing.JTextField();
        jtext1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jfondo.setForeground(new java.awt.Color(0, 0, 0));
        jfondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unnamed.jpg"))); // NOI18N

        jhora.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jhora.setText("12:00:00");
        jhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhoraActionPerformed(evt);
            }
        });

        jtext1.setBackground(new java.awt.Color(38, 6, 56));
        jtext1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtext1.setForeground(new java.awt.Color(255, 255, 255));
        jtext1.setText("     Team:   The Avengers");
        jtext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jtext1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jhora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jfondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jtext1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jhora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jfondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhoraActionPerformed

    private void jtext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new server_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jfondo;
    private javax.swing.JTextField jhora;
    private javax.swing.JTextField jtext1;
    // End of variables declaration//GEN-END:variables
}
